const ALERT = "ALERT";
const REFETCH_CHAT = "REFETCH_CHAT";
const NEW_ATTACHMENT = "NEW_ATTACHMENT";
const NEW_MESSAGE = "NEW_MESSAGE";
const NEW_REQUEST = "NEW_REQUEST";

export { ALERT, REFETCH_CHAT, NEW_ATTACHMENT, NEW_MESSAGE, NEW_REQUEST };
